### ISSUE TITLE
container does not start

### ISSUE THREAD

**Issue by matthiasradde** [threesquared/docker-ezstream#1]
The `,` are missing between the `ENTRYPOINT`-elements within the Dockerfile. Therefore the resulting image is unable to start as the file `/usr/bin/ezstream"` could not be found

So
`ENTRYPOINT ["/usr/bin/ezstream" "-c" "/ezstream/ezstream.xml"]`
should be changed to
`ENTRYPOINT ["/usr/bin/ezstream", "-c", "/ezstream/ezstream.xml"]`

**Comment by threesquared** [comment]
Fixed in #2
